### ISSUE TITLE
Unable to find source map file at: /Users/runner/work/1/s/ios/main.jsbundle.map'

### ISSUE THREAD

**Issue by Harisene** [Instabug/Instabug-React-Native#1086]
I'm running my RN project on App Center and came across this issue when building the iOS app

### SDK Version
12.4.0

### React Native, iOS and Android Versions
0.72.0

**Comment by Harisene** [comment]
here is more info from the logs.

```
+++ EXTRA_COMPILER_ARGS=-O
+++ [[ true == true ]]
+++ EXTRA_COMPILER_ARGS='-O -output-source-map'
+++ /Users/runner/work/1/s/ios/Pods/hermes-engine/destroot/bin/hermesc -emit-binary -max-diagnostic-width=80 '-O -output-source-map' -out /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/main.jsbundle
hermesc: Unknown command line argument '-O -output-source-map'.  Try: '/Users/runner/work/1/s/ios/Pods/hermes-engine/destroot/bin/hermesc -help'
hermesc: Did you mean '-output-source-map'?
+++ [[ true == true ]]
+++ HBC_SOURCEMAP_FILE=/Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map
+++ node /Users/runner/work/1/s/node_modules/react-native/scripts/compose-source-maps.js /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/main.jsbundle.map /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map -o /Users/runner/work/1/s/ios/main.jsbundle.map
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Object.<anonymous> (/Users/runner/work/1/s/node_modules/react-native/scripts/compose-source-maps.js:37:8)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map'
}

Node.js v18.19.0
+++ rm /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map
rm: /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle.map: No such file or directory
+++ rm /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/main.jsbundle.map
+++ BUNDLE_FILE=/Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle
+++ [[ false != true ]]
+++ [[ ! -f /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/BuildProductsPath/Release-iphoneos/Harisene.app/main.jsbundle ]]
++ [[ ! -f /Users/runner/work/1/s/ios/main.jsbundle.map ]]
++ echo '[Error] Unable to find source map file at: /Users/runner/work/1/s/ios/main.jsbundle.map'
++ exit 0
node:fs:596
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '[Error]'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at uploadSourcemaps (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:17519:33)
    at Command.<anonymous> (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:17514:5)
    at Command.listener [as _actionHandler] (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:824:17)
    at /Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:1259:65
    at Command._chainOrCall (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:1191:12)
    at Command._parseCommand (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:1259:27)
    at /Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:1118:27
    at Command._chainOrCall (/Users/runner/work/1/s/node_modules/instabug-reactnative/bin/index.js:1191:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '[Error]'
}

Node.js v18.19.0
Command PhaseScriptExecution failed with a nonzero exit code

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP-User]\ [instabug-reactnative]\ Upload\ Sourcemap /Users/runner/Library/Developer/Xcode/DerivedData/Harisene-fxuxlnbddklfnigvubudxqyeggce/Build/Intermediates.noindex/ArchiveIntermediates/Harisene/IntermediateBuildFilesPath/Harisene.build/Release-iphoneos/Harisene.build/Script-4EAB97A16AFF92CC10858C8E.sh (in target 'Harisene' from project 'Harisene')
(1 failure)
```

**Comment by haozhutw** [comment]
This issue should be reopened, I have same error when upload ios sourcemap. The doc [https://docs.instabug.com/docs/react-native-symbolication-obfuscation#uploading-source-maps-automatically](https://docs.instabug.com/docs/react-native-symbolication-obfuscation#uploading-source-maps-automatically) doesn't work since the `upload_sourcemap.sh` is renamed as `sourcemaps.sh`, I changed the script to 

```
export INSTABUG_APP_TOKEN="mytokenvaluesxxxxxxxxxxx"
bash "../node_modules/instabug-reactnative/ios/sourcemaps.sh"
```
But the build is always failed by this script.
