### ISSUE TITLE
Android crashes when calling Instabug.init

### ISSUE THREAD

**Issue by JohnGoodman** [Instabug/Instabug-React-Native#1182]
Using Instabug 12.2.0 ( but also tried with 12.8.0 and had the same issue ) and react native 0.73.6. 

I run yarn android and the app builds. Open the app and it crashes and shows nothing in the metro logs. There is a Logcat error shown below. The culprit seems to be `Instabug.init({token: instabugKey});`. If I comment out that line, the app runs as expected. The `instabugKey` variable is set and Instabug itself is loaded.

Logcat error
```
java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference
at com.instabug.reactlibrary.utils.ArrayUtil.parseReadableArrayOfStrings(ArrayUtil.java:159)
at com.instabug.reactlibrary.RNInstabugReactnativeModule$2.run(RNInstabugReactnativeModule.java:121)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by JohnGoodman** [comment]
Hey, just let me know what information you need. I know the issue doesn't follow the template, but you should have all relevant info.

**Comment by JohnGoodman** [comment]
The issue was related to having an older version of CrashReporting within my app. It was failing silently so there was no indication that was the problem. After digging into the docs more, I found that I was using an older version of CrashReporting. After updating, this package works on Android again.
