### ISSUE TITLE
Android Crash on version >= 12.7.0

### ISSUE THREAD

**Issue by springer5296** [Instabug/Instabug-React-Native#1193]
### Steps to Reproduce the Problem

1. Set instabug-reactnative version to 12.7.0 or higher. We are using 13.0.0, but experience this in all versions starting at 12.7.0
2. Run react native project on Android
3. App will crash on start.
4. Used log cat to capture error

### Expected Behavior

App starts up like normal. 

### Actual Behavior

App crashes on start. This crash only occurs on Android, not iOS.

Log Captured from LogCat

`
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/visualusersteps/TouchedViewExtractor;
                                                                                                    	at com.instabug.reactlibrary.RNInstabugReactnativeModule.init(RNInstabugReactnativeModule.java:135)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.visualusersteps.TouchedViewExtractor" on path: DexPathList[[zip file "/data/app/~~KbfxvCJWohg8qSXL4lbp_Q==/gokart.com.principal.rndebug-8a9wEkXkW6tBHjO3ngt92g==/base.apk"],nativeLibraryDirectories=[/data/app/~~KbfxvCJWohg8qSXL4lbp_Q==/gokart.com.principal.rndebug-8a9wEkXkW6tBHjO3ngt92g==/lib/arm64, /data/app/~~KbfxvCJWohg8qSXL4lbp_Q==/gokart.com.principal.rndebug-8a9wEkXkW6tBHjO3ngt92g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.instabug.reactlibrary.RNInstabugReactnativeModule.init(RNInstabugReactnativeModule.java:135) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
`

### Instabug integration code

`Instabug.init({
	token: PlatformUtils.isIos() ? iOSToken : androidToken,
	invocationEvents: [instabugInvocationEvent],
});`

### SDK Version

Versions: >= 12.7.0. 

### React Native, iOS and Android Versions

React Native - 0.70.8
Android - 13, 14

### Device Model

Pixel 5 Emulator (Android 13), Samsung Galaxy S22 Ultra (Android 14)

**Comment by springer5296** [comment]
We found we had a dependency lock that was still using an old version. Bumping that to 13.0.0 resolved this. Closing.
