### ISSUE TITLE
Suggest a feature causes crash on Android phones with api level <21

### ISSUE THREAD

**Issue by Seeker93** [Instabug/Instabug-React-Native#203]
I've been facing this issue and it only affects phones running and old Android OS version. New android versions work fine and all iOS versions work fine. I believe it has something to do with vector drawables.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.placeholdername.app/com.instabug.featuresrequest.ui.FeaturesRequestActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class android.widget.ImageView
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	 at android.app.ActivityThread.access$800(ActivityThread.java:166)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:136)
	 at android.app.ActivityThread.main(ActivityThread.java:5590)
	 at java.lang.reflect.Method.invokeNative(Native Method)
	 at java.lang.reflect.Method.invoke(Method.java:515)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	 at dalvik.system.NativeStart.main(Native Method)

Caused by: 
android.view.InflateException: Binary XML file line #26: Error inflating class android.widget.ImageView
	 at android.view.LayoutInflater.createView(LayoutInflater.java:627)
	 at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
	 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
	 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:858)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:858)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	 at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	 at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	 at com.instabug.library.core.ui.BaseFragment.onCreateView(BaseFragment.java:36)
	 at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
	 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
	 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	 at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
	 at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
	 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
	 at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
	 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
	 at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
	 at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
	 at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
	 at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
	 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
	 at android.app.Activity.performStart(Activity.java:5457)
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	 at android.app.ActivityThread.access$800(ActivityThread.java:166)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:136)
	 at android.app.ActivityThread.main(ActivityThread.java:5590)
	 at java.lang.reflect.Method.invokeNative(Native Method)
	 at java.lang.reflect.Method.invoke(Method.java:515)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	 at dalvik.system.NativeStart.main(Native Method)
```

### Steps to Reproduce the Problem

Load app onto Android phone with API level < 21
Enable "Suggest a feature" functionality.
Click suggest a feature

### Expected Behavior

Opens suggest a feature screen

### Actual Behavior
App crashes

### React Native, iOS and Android Versions
RN version: 0.56.1
Instabug-reactnative : 8.0.12 

### Device Model
Any android device with android version 4.4 or less (Api level <21)

**Comment by Korazy** [comment]
Hey @Seeker93 

Thanks for reaching out, we will investigate this and get back to you :)

**Comment by Korazy** [comment]
Would you be able to update to the latest version? It should be fixed there. 

Please let me know if you it's still occurring for you afterwards.

**Comment by Seeker93** [comment]
Hi @Korazy I installed the latest instabug-react-native version and the same issue (and same error) came up. Unfortunately , it doesn't look it it has been resolved.

**Comment by Korazy** [comment]
That is odd, I will look into this and update you as soon as i can :)

**Comment by Korazy** [comment]
@Seeker93 sorry for the delay. Would you be able to download the latest version now and try again? :)

**Comment by Korazy** [comment]
@Seeker93 was the issue fixed for you?

**Comment by Seeker93** [comment]
HI @Korazy I just upgraded to 8.0.16. Unfortunately the issue still occurs. Are you able to reproduce it?

**Comment by Peter-Ayad** [comment]
@Seeker93 Please let me check this for you further from my side and we will get back to you.

**Comment by Korazy** [comment]
Hey @Seeker93 

We created a custom build just for you and hopefully it resolves the issue. To install this build, please run the following
npm install --save https://github.com/Instabug/Instabug-React-Native/tree/customBuild/snapshot_8.0.11.11

Please let me know if it works.

**Comment by Korazy** [comment]
Please feel free to reopen the issue should it occur again :)
