### ISSUE TITLE
Cannot react-native link latest(v8.0.12) for iOS

### ISSUE THREAD

**Issue by jsmankoo** [Instabug/Instabug-React-Native#204]
### Steps to Reproduce the Problem
- yarn add instabug-reactnative
- react-native link instabug-reactnative

### Expected Behavior
- Successfully links native module.

### Actual Behavior
```
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x00007f90d58ca510> (NoMethodError)
Did you mean?  to_s
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./node_modules/instabug-reactnative/link.rb:25:in `<main>'
/Users/jsmankoo/Indigofair/rn-app/node_modules/react-native/local-cli/core/makeCommand.js:32
        throw new Error(`Error occurred during executing "${command}" command`);
```

### Instabug integration code
N/A

### SDK Version
v8.0.12

### React Native, iOS and Android Versions
react-native@0.56.0, iOS v11.4, Android N/A

### Device Model
N/A

**Comment by Korazy** [comment]
Hey @jsmankoo 

Apologies for the late response, I am investigating this and will get back to you as soon as possible :)

**Comment by jsmankoo** [comment]
Np!

**Comment by Korazy** [comment]
Would you be able to  update your `xcodeproj` using `gem install xcodeproj`?

**Comment by Korazy** [comment]
@jsmankoo did you get a chance to update your `xcodeproj` using `gem install xcodeproj`?

**Comment by jsmankoo** [comment]
Sorry haven't gotten a chance to get back to app. I'll message as soon as I get the opportunity to.

**Comment by Korazy** [comment]
Hey @jsmankoo

Did you get a chance to try it out?

**Comment by Korazy** [comment]
Feel free to reopen the issue should it occur again :)
