### ISSUE TITLE
[CRASH on sdk 2.13.3] -: Attempt to invoke virtual method 'int com.instabug.library.settings.a.n()' on a null object reference

### ISSUE THREAD

**Issue by abrel** [Instabug/Instabug-React-Native#213]
I am getting this error on Crashlytics 
It happens on Android only and I could not reproduce it myself.

### SDK Version
2.13.3

### React Native, iOS and Android Versions
- RN 0.57.4

### Device Model
- SM-G955F (android 8.0.0)
-  G3311 (android 7.0)

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.instabug.library.settings.a.n()' on a null object reference
       at com.instabug.library.settings.SettingsManager.getStatusBarColor(SettingsManager.java:365)
       at com.instabug.library.util.StatusBarUtils.setStatusBar(StatusBarUtils.java:27)
       at com.instabug.library.core.ui.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:31)
       at com.instabug.library.invocation.invocationdialog.InstabugDialogActivity.onCreate(InstabugDialogActivity.java:54)
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6368)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by ramiimagdi** [comment]
Hey @abrel,
Thank you for reaching out to us. Please allow me some time to investigate this further and get back to you as fast as possible.

**Comment by ramiimagdi** [comment]
I was wondering @abrel if you could give it a shot and update to our latest version. As version 2.13.3 is extremely old and misses a lot of fixes.

Thank you!

**Comment by rdiaa** [comment]
Hello @abrel, I was checking if you had the chance to update to our latest version of RN and check if the issue still exists.

**Comment by abrel** [comment]
Hello,
I will try that and keep you posted

**Comment by rdiaa** [comment]
Perfect, I will be waiting

**Comment by rdiaa** [comment]
@abrel did you have the chance to update the latest version of RN?

**Comment by rdiaa** [comment]
@abrel please feel free to reopen the issue if anything is not in place after you update RN to the latest version.
