### ISSUE TITLE
Crash : Error an Android with getTextFromFile

### ISSUE THREAD

**Issue by tgensol** [Instabug/Instabug-React-Native#218]
Hi,

Since a couple of days I am getting this error on Android: 

```
ReadStateFromFileDiskOperation.java line 52
com.instabug.library.internal.storage.operation.ReadStateFromFileDiskOperation.getTextFromFile
```

Caused by

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 11665048 byte allocation with 5094856 free bytes and 4MB until OOM, max allowed footprint 268435456, growth limit 268435456
       at java.lang.StringFactory.newStringFromChars(StringFactory.java:220)
       at java.lang.StringBuffer.toString(StringBuffer.java:671)
       at java.io.BufferedReader.readLine(BufferedReader.java:338)
       at java.io.BufferedReader.readLine(BufferedReader.java:400)
       at com.instabug.library.internal.storage.operation.ReadStateFromFileDiskOperation.getTextFromFile(ReadStateFromFileDiskOperation.java:52)
       at com.instabug.library.internal.storage.operation.ReadStateFromFileDiskOperation.execute(ReadStateFromFileDiskOperation.java:26)
       at com.instabug.library.internal.storage.operation.ReadStateFromFileDiskOperation.execute(ReadStateFromFileDiskOperation.java:16)
       at com.instabug.library.internal.storage.executor.ReadOperationExecutor.execute(ReadOperationExecutor.java:19)
       at com.instabug.crash.a.a.a(CrashReportsDbHelper.java:110)
       at com.instabug.crash.network.InstabugCrashesUploaderService.b(InstabugCrashesUploaderService.java:99)
       at com.instabug.crash.network.InstabugCrashesUploaderService.runBackgroundTask(InstabugCrashesUploaderService.java:57)
       at com.instabug.library.network.a.onHandleWork(InstabugBackgroundService.java:28)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

It looks like it only happens with Android 9 and 8 device with the latest version of Instabug for RN.

I am using crashlytics, and I found this issue which sounds familiar : https://github.com/Instabug/Instabug-Android/issues/110

I am also getting another error : 
```

Caused by java.lang.OutOfMemoryError
Failed to allocate a 82481736 byte allocation with 4194304 free bytes and 77MB until OOM
com.instabug.library.model.State.fromJson
```

`Caused by java.lang.OutOfMemoryError: Failed to allocate a 82481736 byte allocation with 4194304 free bytes and 77MB until OOM
       at java.lang.StringBuilder.toString(StringBuilder.java:408)
       at org.json.JSONTokener.nextString(JSONTokener.java:211)
       at org.json.JSONTokener.nextValue(JSONTokener.java:107)
       at org.json.JSONTokener.readObject(JSONTokener.java:384)
       at org.json.JSONTokener.nextValue(JSONTokener.java:100)
       at org.json.JSONObject.<init>(JSONObject.java:156)
       at org.json.JSONObject.<init>(JSONObject.java:173)
       at com.instabug.library.model.State.fromJson(State.java:551)
       at com.instabug.crash.a.a.a(CrashReportsDbHelper.java:111)
       at com.instabug.crash.network.InstabugCrashesUploaderService.b(InstabugCrashesUploaderService.java:99)
       at com.instabug.crash.network.InstabugCrashesUploaderService.runBackgroundTask(InstabugCrashesUploaderService.java:57)
       at com.instabug.library.network.a.onHandleWork(InstabugBackgroundService.java:28)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
       at android.os.AsyncTask$2.call(AsyncTask.java:316)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)`

And it looks like it happens only on Android 5 and 7 Device,

Thanking you in advance,
Best regards

**Comment by tgensol** [comment]
Hi @rdiaa ,

Thanks for the quick fix ! I will try it today and see how it goes. I am also getting some errors which maybe are related, so I will wait a few days to see.

Best

**Comment by tgensol** [comment]
It looks like you upgrade the compileSdkVersion and targetSdkVersion to 28, so I had to change them also in my project, because it was impossible to compile (I was getting missing stuff from android libraires like compat or design)

**Comment by rdiaa** [comment]
@tgensol Please, let me know if you need any assistance from my side. I'm glad that you figured it out. After you install the custom build, let me know if you are facing any issues.

**Comment by tgensol** [comment]
It looks like to be working well on my side, but I will wait a few days to have more data and users with the fix.

Thanks again,
Best

**Comment by rdiaa** [comment]
Great, I'm glad that everything is working fine on your end. please reopen the issue if anything is not on the place after your testing.

**Comment by mattetre** [comment]
@rdiaa Is there a timeline on when these fixes will be rolled into a release or should others experiencing this issue look to use the custom build steps provided above?
