### ISSUE TITLE
Bundling failed. Unable to resolve module `./utils/NetworkInterceptor.js`

### ISSUE THREAD

**Issue by evaleirasclapps** [Instabug/Instabug-React-Native#244]
### Steps to Reproduce the Problem
`react-native run-ios`

### Expected Behavior

> Start the application.

### Actual Behavior
```
error: bundling failed: Error: Unable to resolve module ./utils/NetworkInterceptor.js from /Users/user/workspace/Project/node_modules/instabug-reactnative/index.js: The module ./utils/NetworkInterceptor.js could not be found from /Users/user/workspace/Project/node_modules/instabug-reactnative/index.js. Indeed, none of these files exist:

  * /Users/user/workspace/Project/node_modules/instabug-reactnative/utils/NetworkInterceptor.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)
  * /Users/user/workspace/Project/node_modules/instabug-reactnative/utils/NetworkInterceptor.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/user/workspace/Project/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
    at ResolutionRequest.resolveDependency (/Users/user/workspace/Project/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/user/workspace/Project/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/user/workspace/Project/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/user/workspace/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/user/workspace/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/user/workspace/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/user/workspace/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
```

### SDK Version

**8.0.24**

### React Native, iOS and Android Versions
React-Native: **0.56.0**

### Device Model

**iPhone 7**

**Comment by salmamali** [comment]
@evaleirasclapps Did you recently upgrade from an older version? It may be you need to just clean your cache. Try running the following to reset everything.
```watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && npm install && npm start -- --reset-cache```

**Comment by HeshamMegid** [comment]
Closing this issue as we haven't heard back from you. Please feel free to reopen if the solution above hasn't fixed the problem.
