### ISSUE TITLE
8.0.26 java.lang.RuntimeException: Unable to start activity ComponentInfo{mycompany/com.instabug.library.ui.Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.b.h(boolean)' on a null object reference

### ISSUE THREAD

**Issue by JinghaoYJH** [Instabug/Instabug-React-Native#271]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{mycompany/com.instabug.library.ui.Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.b.h(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

### SDK Version
8.0.26

### React Native, iOS and Android Versions
React Native 0.58.4
Android 9

**Comment by HeshamMegid** [comment]
@JinghaoYJH we're looking into this and will get back to you soon.
