### ISSUE TITLE
BugReporting.setInvocationEvents() function does not work on Android at runtime

### ISSUE THREAD

**Issue by cpetzel** [Instabug/Instabug-React-Native#273]
Our app toggles the Instabug bubble on and off based on certain conditions via the `BugReporting.setInvocationEvents()` function. 
When we try to toggle it back on, the bubble never appears. See gif below

### Steps to Reproduce the Problem

To debug this, I verified that the  SDK's `InvocationManager` is updated with the latest values by putting debug statements in the `setInvocationEvents` method. 

![instabug issue mov](https://user-images.githubusercontent.com/2036206/56628271-061a5b80-65fe-11e9-9774-24a72658742d.gif)

```java
@ReactMethod
    public void setInvocationEvents(ReadableArray invocationEventValues) {

        try {
            Object[] objectArray = ArrayUtil.toArray(invocationEventValues);
            String[] stringArray = Arrays.copyOf(objectArray, objectArray.length, String[].class);
            final ArrayList<InstabugInvocationEvent> parsedInvocationEvents = new ArrayList<>();

            for (String action : stringArray) {
                switch (action) {
                    case INVOCATION_EVENT_FLOATING_BUTTON:
                        parsedInvocationEvents.add(InstabugInvocationEvent.FLOATING_BUTTON);
                        break;
                    case INVOCATION_EVENT_TWO_FINGERS_SWIPE:
                        parsedInvocationEvents.add(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT);
                        break;
                    case INVOCATION_EVENT_SHAKE:
                        parsedInvocationEvents.add(InstabugInvocationEvent.SHAKE);
                        break;
                    case INVOCATION_EVENT_SCREENSHOT:
                        parsedInvocationEvents.add(InstabugInvocationEvent.SCREENSHOT);
                        break;
                    case INVOCATION_EVENT_NONE:
                        parsedInvocationEvents.add(InstabugInvocationEvent.NONE);
                        break;
                    default:
                        parsedInvocationEvents.add(InstabugInvocationEvent.SHAKE);
                        break;
                }
            }
            new Handler(Looper.getMainLooper()).post(new Runnable() {
                @Override
                public void run() {
                    try {
                  InstabugInvocationEvent[] currentInstabugInvocationEvents = InvocationManager.getInstance().getCurrentInstabugInvocationEvents();
                        Log.d("INSTABUG_DEBUG", "Instabug before currentInstabugInvocationEvents" + Arrays.toString(currentInstabugInvocationEvents));

                        BugReporting.setInvocationEvents(parsedInvocationEvents.toArray(new InstabugInvocationEvent[0]));

                        currentInstabugInvocationEvents = InvocationManager.getInstance().getCurrentInstabugInvocationEvents();
                        Log.d("INSTABUG_DEBUG", "Instabug after currentInstabugInvocationEvents" + Arrays.toString(currentInstabugInvocationEvents));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

```

Here is the javascript that I used to find the bug... 

```javascript
let enabled = false;
setInterval(() => {
  if (enabled) {
    console.log("[Instabug] - turning off instabug");
    BugReporting.setInvocationEvents([Instabug.invocationEvent.none]);
  } else {
    console.log("[Instabug] - turning on instabug");
    BugReporting.setInvocationEvents([Instabug.invocationEvent.floatingButton]);
  }
  enabled = !enabled;
}, 2000); 
```

### Expected Behavior
I expect to see the instabug bubble appear and reappear if I toggle it during runtime. 

### Actual Behavior
After I toggle the instabug bubble off, it will never reappear. 

### Instabug integration code
```java
    new RNInstabugReactnativePackage.Builder("token",MainApplication.this)
							.setInvocationEvent("none") // this will be enabled by JS
							.setPrimaryColor("#FD4452")
                            .setCrashReportingEnabled(false)
                            .setFloatingEdge("right")
							.setFloatingButtonOffsetFromTop(480)
							.build(),
```
### SDK Version
8.2.5
### React Native, iOS and Android Versions
React Native 0.57.4

### Device Model
All Android devices

Not sure if this is related, but I do see a stack trace error when starting my application...

```
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.instabug.library.invocation.InvocationManager.getFloatingButtonInvoker(InvocationManager.java:520)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.instabug.library.invocation.InvocationManager.notifyInvocationOptionChanged(InvocationManager.java:507)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.instabug.bug.c.a(BugReportingWrapper.java:154)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.instabug.bug.BugReporting.setState(BugReporting.java:445)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.instabug.reactlibrary.RNInstabugReactnativeModule$13.run(RNInstabugReactnativeModule.java:1631)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at android.os.Handler.handleCallback(Handler.java:873)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at android.os.Handler.dispatchMessage(Handler.java:99)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at android.os.Looper.loop(Looper.java:193)	
04-23 19:31:03.461	co.scoot.scootapp.debug	23734	-	W	System.err	 	at android.app.ActivityThread.main(ActivityThread.java:6669)	
04-23 19:31:03.462	co.scoot.scootapp.debug	23734	-	W	System.err	 	at java.lang.reflect.Method.invoke(Native Method)	
04-23 19:31:03.462	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	
04-23 19:31:03.462	co.scoot.scootapp.debug	23734	-	W	System.err	 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)	

```

**Comment by cpetzel** [comment]
This bug is also visible in the `InstabugSample` Android app on latest master. 

Clicking between `NONE` and `FLOATING BUTTON` does not work. However, clicking between `SHAKE` and `FLOATING BUTTON` works as intended... 

![instademo mov](https://user-images.githubusercontent.com/2036206/56636226-f4947c00-661c-11e9-9fb5-a8972d403b37.gif)

**Comment by salmamali** [comment]
@cpetzel Thank you for the detailed report. We'll be looking into this issue.
