### ISSUE TITLE
Application crashing: Instabug getInstance called before Instabug.Builder().build() was called

### ISSUE THREAD

**Issue by mcnestrb** [Instabug/Instabug-React-Native#403]
### Steps to Reproduce the Problem
Build and open the app.
The app builds successfully on Android but crashes immediately when it is opened with the following error. The app runs successfully with Instabug on iOS

```
java.lang.IllegalStateException: Instabug getInstance called before Instabug.Builder().build() was called
    at com.instabug.library.Instabug.getInstance(Instabug.java:84)
    at com.instabug.library.Instabug.getApplicationContext(Instabug.java:95)
    at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance(DatabaseManager.java:26)
    at com.instabug.library.logging.b.a(InstabugNetworkLogDbHelper.java:22)
    at com.instabug.library.model.NetworkLog.insert(NetworkLog.java:161)
    at com.instabug.reactlibrary.RNInstabugReactnativeModule.networkLog(RNInstabugReactnativeModule.java:1874)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:764)
```
### Expected Behavior
The application opens and we can use our application
### Actual Behavior
On start-up an error is thrown with the message `Instabug getInstance called before Instabug.Builder().build() was called`
### Instabug integration code
```
packages.add(
  new RNInstabugReactnativePackage
    .Builder("APP_TOKEN", MainApplication.this)
    .setInvocationEvent("shake")
    .setPrimaryColor("#1D82DC")
    .setFloatingEdge("left")
    .setFloatingButtonOffsetFromTop(250)
    .build()
);
```

### SDK Version

`8.6.4`
### React Native, iOS and Android Versions
react-native `0.60.5`

### Device Model

All Android devices including Android Studio emulators

**Comment by phiilu** [comment]
I get the same error on Android

**Comment by alyezz** [comment]
@mcnestrb @phiilu Yes you are correct, since our library supports autolinking, the integration code should be in the `onCreate()` method as follows: 
```
 @Override
  public void onCreate() {
    new RNInstabugReactnativePackage
            .Builder("APP_TOKEN", MainApplication.this)
            .setInvocationEvent("shake")
            .setPrimaryColor("#1D82DC")
            .setFloatingEdge("left")
            .setFloatingButtonOffsetFromTop(250)
            .build();
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
```

Since this is just an initialization of the native SDK instead of actually linking the package with react native. 

I will update the repo's readme to reflect this change, sorry about that.

**Comment by mcnestrb** [comment]
This worked perfectly 😄 thanks @alyezz and @phiilu ❤️
