### ISSUE TITLE
Crashes on android (samsung J6+)

### ISSUE THREAD

**Issue by AlexHolubDoIt** [Instabug/Instabug-React-Native#434]
Crash on samsung and huawei devices, happens when device is in background. We are using react-native-background-geolocation and react-native-background-uploading, hope this can help to solve the issue

```

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
	 at com.instabug.library.PresentationManager.show(PresentationManager.java:40)
	 at com.instabug.library.b.b(InstabugDelegate.java:496)
	 at com.instabug.library.b.a(InstabugDelegate.java:403)
	 at com.instabug.library.b$7.run(InstabugDelegate.java:344)
	 at android.os.Handler.handleCallback(Handler.java:751)
	 at android.os.Handler.dispatchMessage(Handler.java:95)
	 at android.os.Looper.loop(Looper.java:154)
	 at android.app.ActivityThread.main(ActivityThread.java:6682)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

```
### Steps to Reproduce the Problem
install intabug from sdk-integration page
### Expected Behavior
app not crashed on android
### Actual Behavior
app is crashed on android
### Instabug integration code
settings.gradle
```
include ':instabug-reactnative'
project(':instabug-reactnative').projectDir = new File(rootProject.projectDir, '../node_modules/instabug-reactnative/android')

```
app/build.gradle
```
dependencies {
    implementation project(':instabug-reactnative')
    ...
}

```
mainApplication.java
```
import com.instabug.reactlibrary.RNInstabugReactnativePackage;
...
protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
  new RNInstabugReactnativePackage.Builder("token", MainApplication.this)
            		.setInvocationEvent("shake")
            		.build(),
      );
}

```
### SDK Version
"instabug-reactnative": "^8.7.3"
### React Native, iOS and Android Versions
React native 0.58.5
### Device Model
most crashes is on Samsung Galaxy J6+, but was few crashes on Huawei P8 lite and on other Samsung devices

**Comment by alyezz** [comment]
@AlexHolubDoIt thanks for the report, this issue was fixed will be included in our next release, we'll let you know once it's released

**Comment by alyezz** [comment]
@AlexHolubDoIt we just release v9.0.0, this release includes a fix for this issue.

Feel free to reopen this if you still have any issues
