### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by bscheideldyrt** [Instabug/Instabug-React-Native#449]
### Steps to Reproduce the Problem

Unknown, seeing this error in Sentry logs.

### Expected Behavior

No crashes.

### Actual Behavior

````
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference
    at com.instabug.library.internal.storage.cache.user.a.a(UserDbHelper.java:66)
    at com.instabug.library.internal.storage.cache.user.UserCacheManager.insertIfNotExists(UserCacheManager.java:2)
    at com.instabug.library.user.b.g(UserManager.java:20)
    at com.instabug.library.internal.storage.cache.db.userAttribute.UserAttributeCacheManager.retrieveAll(UserAttributeCacheManager.java:1)
    at com.instabug.library.internal.storage.cache.db.userAttribute.UserAttributesDbHelper.getAll(UserAttributesDbHelper.java:1)
    at com.instabug.library.g.g(SessionManager.java:1)
    at com.instabug.library.g.a(SessionManager.java:6)
    at com.instabug.library.g.f(SessionManager.java:2)
    at com.instabug.library.g.m(SessionManager.java:3)
    at com.instabug.library.g.b(SessionManager.java:4)
    at com.instabug.library.tracking.b.onTrimMemory(InstabugActivityLifecycleListener.java:7)
    at android.app.Application.onTrimMemory(Application.java:149)
    at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5687)
    at android.app.ActivityThread.access$900(ActivityThread.java:213)
    at android.app.ActivityThread$ApplicationThread.lambda$scheduleTrimMemory$0(ActivityThread.java:1462)
    at android.app.-$$Lambda$ActivityThread$ApplicationThread$tUGFX7CUhzB4Pg5wFd5yeqOnu38.accept
    at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:258)
    at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)
    at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:698)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:215)
    at android.app.ActivityThread.main(ActivityThread.java:6939)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
````

### Instabug integration code

````
        // Set up Instabug but turn off all events, we'll enable these at runtime
        new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_KEY, MainApplication.this)
          .setInvocationEvent("none")
          .build();
````

### SDK Version
9.0.1

### React Native, iOS and Android Versions
React-Native:  0.61.4
Android: Android 9

### Device Model
Moto Z4

**Comment by alyezz** [comment]
@bscheideldyrt Thanks for the report, how many occurrences did you find? and are you able to reproduce it?

**Comment by bscheideldyrt** [comment]
This has been hit by 3 users so far.  We haven't been able to reproduce it.  Can you tell if this is on app boot or when somebody actually tries to log an issue?

**Comment by alyezz** [comment]
@bscheideldyrt This crash happened upon app termination, we will add some defensive code to prevent it from happening, we will let you know once this is released.

Thanks!

**Comment by alyezz** [comment]
@bscheideldyrt the fix is included in out latest release. Feel free to reopen this if you're still facing this issue
