### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294 SQLITE_CANTOPEN_ENOENT[1294]): Could not open database

### ISSUE THREAD

**Issue by bscheideldyrt** [Instabug/Instabug-React-Native#450]
### Steps to Reproduce the Problem

Unknown, seeing this error in Sentry logs.

### Expected Behavior

No crashes.

### Actual Behavior

````
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294 SQLITE_CANTOPEN_ENOENT[1294]): Could not open database
    at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:284)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:705)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:272)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:239)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1292)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1247)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:903)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:893)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
    at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.open(SQLiteDatabaseWrapper.java:3)
    at com.instabug.library.internal.storage.cache.db.DatabaseManager.openDatabase(DatabaseManager.java:1)
    at com.instabug.library.internal.storage.cache.db.userAttribute.UserAttributesDbHelper.retrieveAll(UserAttributesDbHelper.java:1)
    at com.instabug.library.internal.storage.cache.db.userAttribute.UserAttributeCacheManager.retrieveAll(UserAttributeCacheManager.java:1)
    at com.instabug.library.internal.storage.cache.db.userAttribute.UserAttributesDbHelper.getAll(UserAttributesDbHelper.java:1)
    at com.instabug.library.g.g(SessionManager.java:1)
    at com.instabug.library.g.a(SessionManager.java:6)
    at com.instabug.library.g.f(SessionManager.java:2)
    at com.instabug.library.g.m(SessionManager.java:3)
    at com.instabug.library.g.b(SessionManager.java:4)
    at com.instabug.library.tracking.b.onTrimMemory(InstabugActivityLifecycleListener.java:7)
    at android.app.Application.onTrimMemory(Application.java:174)
    at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5823)
    at android.app.ActivityThread.access$1000(ActivityThread.java:241)
    at android.app.ActivityThread$ApplicationThread.lambda$scheduleTrimMemory$0(ActivityThread.java:1551)
    at android.app.-$$Lambda$ActivityThread$ApplicationThread$tUGFX7CUhzB4Pg5wFd5yeqOnu38.accept
    at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:258)
    at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)
    at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
    at android.view.Choreographer.doCallbacks(Choreographer.java:765)
    at android.view.Choreographer.doFrame(Choreographer.java:702)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7156)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
````

### Instabug integration code

````
        // Set up Instabug but turn off all events, we'll enable these at runtime
        new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_KEY, MainApplication.this)
          .setInvocationEvent("none")
          .build();
````

### SDK Version
9.0.1

### React Native, iOS and Android Versions
React-Native:  0.61.4
Android: Android 9

### Device Model
SM-S367VL

**Comment by alyezz** [comment]
@bscheideldyrt Thanks for the report, how many occurrences did you find? and are you able to reproduce it?

**Comment by bscheideldyrt** [comment]
This has been hit by 1 user so far.  We haven't been able to reproduce it.

**Comment by alyezz** [comment]
@bscheideldyrt This crash happened upon app termination, we will add some defensive code to prevent it from happening, we will let you know once this is released.

Thanks!

**Comment by alyezz** [comment]
@bscheideldyrt the fix is included in out latest release. Feel free to reopen this if you're still facing this issue

**Comment by IlyaGazman** [comment]
Hey, @alyezz this happens to me all the time on my local testing, using 'io.requery:sqlite-android:3.33.0'

It happens when upgrading from an old version to anew version of my app, only in release build and it's only crashing once, during the first launch.

What kind of demon is this, lol?

My old app is using 'io.requery:sqlite-android:3.28.0', I tested this on Pixel 2


```
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294 SQLITE_CANTOPEN_ENOENT[1294]): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:300)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1394)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1339)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1001)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:940)
        at com.facebook.oxygen.common.androidx.workmanager.initializer.b.a(WorkManagerDatabase.java:20)
        at com.facebook.oxygen.appmanager.app.c.b(AppManagerApplicationImpl.java:19)
        at com.facebook.oxygen.common.e.b.d.onCreate(OxpDelegatingApplication.java:68)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7184)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
        at android.app.ActivityThread.access$1600(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
