### ISSUE TITLE
Sourcemap upload fails for android on 9.1.7

### ISSUE THREAD

**Issue by AndrewMorsillo** [Instabug/Instabug-React-Native#510]
### Steps to Reproduce the Problem
`./gradlew assembleRelease` with instabug 9.1.7

### Expected Behavior
Sourcemaps upload correctly

### Actual Behavior
Sourcemap upload task fails with

```
> Task :instabug-reactnative:upload_sourcemap
Instabug: Looking for Token...
Instabug: Token found "MY_TOKEN_HERE"
Instabug: Version Code found "1599068100"
Instabug: Version Name found "2.0.9"
Instabug: Generating sourcemap files...
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


Assertion failed: (!uv__is_closing(handle)), function uv_close, file ../deps/uv/src/unix/core.c, line 113.
./upload_sourcemap.sh: line 74: 19576 Abort trap: 6           react-native bundle --platform android --reset-cache --entry-file index.js --dev false --bundle-output index.android.bundle --sourcemap-output index.android.bundle.packager.map
cp: index.android.bundle.hbc.map: No such file or directory
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'index.android.bundle.packager.map'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.<anonymous> (/Users/imagio/dev/TaskHero/node_modules/react-native/scripts/compose-source-maps.js:33:43)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'index.android.bundle.packager.map'
}
Instabug: Uploading files...
curl: (26) Failed to open/read local data from file/application
```

### Instabug integration code
Exactly per most recent docs.

### SDK Version
9.1.7

### React Native, iOS and Android Versions
RN 0.63.2

### Device Model
N/A

**Comment by AliAbdelfattah** [comment]
@AndrewMorsillo thanks for reporting this. We're looking into it.

**Comment by AndrewMorsillo** [comment]
@AliAbdelfattah Source map upload is still broken in `https://github.com/Instabug/Instabug-React-Native#snapshot/9.1.8-hide-view-defensive`
